### ISSUE TITLE
Security Warning

### ISSUE THREAD

**Issue by paurray** [DeligenceTechnologies/DT-FastSpring-Payment-for-HikaShop#1]
I got a security warning in Safari and Firefox when going from the last page of the Hika Shop Cart to the order form at Fast Spring. Adding a “s” to http in line 58 in the fastspring.php file seemed to get ride of this problem! I would imagine that depeding on browser setting this might behave differently on different browsers!

`			$this->payment_params->payment_url = "https://sites.fastspring.com/".$this->payment_params->company_id."/api/order";`

FYI: The warning read as follows:

Security Warning

the information you have entered is to be sent over an insecure connection and could be read by a third party.

**Comment by deligence** [comment]
Thanks for reporting this issue. Actually this issue is not due to this plugin. Whenever you'll move from a secure connection (https) to non-secure connection (http) - you'll get the error. The solution is what you have done - we need to make sure that we have Secure connection at all the places.
